### ISSUE TITLE
Class referenced in the layout file, com.github.pelmenstar1.RangeCalendarView, was not found in the project or the libraries

### ISSUE THREAD

**Issue by shahzad1** [pelmenstar1/RangeCalendar#6]
Hi, I'm trying this library but getting error while adding the calendar in XML. I'm also getting this message after **sync**
`Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'RangeCalendarTest', project ':app'
`

**Comment by pelmenstar1** [comment]
Hi @shahzad1. Sorry for the late response. I fixed the misleading README. The RangeCalendarView's package is `com.github.pelmenstar1.rangecalendar` actually.

As for the warning, are you sure that's because of the library because there's no usage of `jcenter()`.

**Comment by pelmenstar1** [comment]
I will close the issue as the problem with README has been fixed and the warning is unrelated to this project.
